<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
    <Folder Include="Models\" />
    <Folder Include="BackgroundServices\" />
    <Folder Include="Validation\" />
    <Folder Include="Services\" />
    <Folder Include="Rooms\Models\" />
    <Folder Include="Signaling\" />
    <Folder Include="WebSockets\Handlers\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" Version="3.2.1" />
  </ItemGroup>

</Project>
